apiVersion: v1
kind: Service
metadata:
  name: static-website-service
  labels:
    app: static-website
spec:
  type: NodePort
  selector:
    app: static-website
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  sessionAffinity: None
