apiVersion: v1
kind: Service
metadata:
  name: static-website-service
  labels:
    app: static-website
spec:
  type: LoadBalancer
  selector:
    app: static-website
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
